### ISSUE TITLE
add info in manual that ttf fonts are not bundled

### ISSUE THREAD

**Issue by matkoniecz** [prawnpdf/prawn#1023]
text/single_usage.rb example in manual has code that will not work without adding ttf files to to {Prawn::DATADIR}

It would be helpful to include instructions how one should obtain files necessary to enable UTF8 support.

See also https://github.com/prawnpdf/prawn/issues/841

**Comment by matkoniecz** [comment]
For example I downloaded https://github.com/prawnpdf/prawn/blob/master/data/fonts/Dustismo_Roman.ttf and I have no idea whatsoever whatever it is the correct way to use characters beyond ASCII.

**Comment by pointlessone** [comment]
Examples in manual are not supposed to be Copy-Paste snippets. They're illustrations of usage. They *are* executable examples but are only meant to run within the repo. We took not a very ergonomic approach but it mostly works well. It lets us be sure that the code in manual is valid and that output is exactly what Prawn would produce.

> I have no idea whatsoever whatever it is the correct way to use characters beyond ASCII.

Font files are not expected to provide any particular character set (including ASCII). Technically, font files can include glyphs that are not mapped to any particular character. They also can include no glyphs at all. It's not very useful but spec doesn't prohibit it. So you have to make sure the font you use is suitable for your text. I believe Prawn (or rather TTFunk) would let you know when text contain characters that font have no glyphs for.

> It would be helpful to include instructions how one should obtain files necessary to enable UTF8 support.

Fonts in Prawn repo are not any special. They're just the ones that let us use them in testing. We are not certain if we can distribute them. So we don't. We intentionally do not package them because of this.

You can find a bunch of freely available fonts on the Internet. You should not use fonts from Prawn repo. Most of these fonts have newer versions available. The older versions in the repo are good enough for our purpose — testing.

As for instructions, I doubt their usefulness as they would be very vague: search the web and make sure the font has glyphs you need. That is about as detailed it can get. We don't want to endorse any specific places you can get fonts from. There are a plenty. Chose your favourite.

---

I will close this issue now. Feel free to reopen.
