### ISSUE TITLE
Need helping understanding a problem where all content is mirrored vertically

### ISSUE THREAD

**Issue by ndbroadbent** [prawnpdf/prawn#1043]
Hello,

I realize that prawn-templates is not officially supported, but I've looked at the prawn-templates code and it seems very sparse, with only a couple of files. So I think my issue is actually in the main prawn library.

This issue has been reported before:

* #568
* #393

And [this StackOverflow answer](https://stackoverflow.com/a/12089301/304706) seems promising, but I still need a lot of help understanding "mirroring text matrixes".

I've followed the steps in the SO answer to fix the flipped text by replacing `286.55 797.384 Td` with `1 0 0 -1 286.55 797.384 Tm`. That seems like a good start, but the positions are still inverted. And I need to figure out how to apply this matrix to some rectangles.

At this point I would just be happy with a workaround to strip the unusual matrices from these pdfs. I've tried various flags with the `qpdf` and `pdftk` command line tools, but the output pdfs still have the same problem.

I've also opened an issue on the `prawn-templates` repo: https://github.com/prawnpdf/prawn-templates/issues/19

Thanks!

**Comment by ndbroadbent** [comment]
Some progress. I ran `qpdf --qdf <original_pdf> <qdf_file>`, then opened the file in my text editor, and saw the following content:

```
%% Contents for page 1
%% Original object ID: 11 0
5 0 obj
<<
  /Length 6 0 R
>>
stream
1 0 0 -1 0 792 cm
```

I changed this to:

```
stream
1 0 0 1 0 0 cm
```

Then I ran:

```
qpdf <qdf_file> <output-fixed>
```

Now the content that Prawn added is correct, but the original template content is vertically inverted.


How can I apply this `1 0 0 -1 0 792 cm` transformation to all content that Prawn renders?

**Comment by ndbroadbent** [comment]
Success! I just needed to call: `pdf.transformation_matrix(1, 0, 0, -1, 0, 792)`. Now the last step is to get this working automatically from `prawn-templates`.

**Comment by pointlessone** [comment]
Hello Nathan,

As you correctly noted prawn-template is not supported any more. But it's the one responsible for *reading* the template, including all the transformation matrices. Prawn only supports *generation* of new documents or content. Prawn doesn't guess what transformation matrix it needs to apply to your text to make it appear right side up on the page. Unless you explicitly specify it, no matrix is applied. It's assumed you're keeping track of graphic state (and transformation matrices). Prawn also doesn't provide any tools for *modification* of documents. You may try using PDF::Core and manually modify objects but I can't tell if that would result in a well-formed document or a broken one.

That said, I don't think it's a bug in Prawn or prawn-template. You just happen to have a weird template. The text inserted withing upside down page appears upside down. This is absolutely reasonable. Since you believe it's a bug you may work on a patch but keep in mind that most of the time applied transformation matrix is intentional. Simply removing it or applying reverse matrix to all text won't be accepted.

---

Thank you for your contribution. I will close this issue now. Feel free to reopen if you have any further feedback.

**Comment by ndbroadbent** [comment]
Thanks for the reply @pointlessone. I agree that these are weird templates, but this issue is happening for **all** PDFs downloaded from Google Docs, or printed as PDFs by Google Chrome. So I think it's an important thing to fix in `prawn-templates`. So I will keep going over at https://github.com/prawnpdf/prawn-templates/issues/19.
