### ISSUE TITLE
zeroPaddedFilemode: contains zero-padded file modes

### ISSUE THREAD

**Issue by xbeta** [prawnpdf/prawn#1071]
Does the git repo has some issue?  I am starting on a side project that's not mine, and simply run `bundle install` and got these issues.

```
# Gemfile
gem 'prawn', git: 'https://github.com/prawnpdf/prawn.git', require: false
gem 'prawn-table', git: 'https://github.com/prawnpdf/prawn-table.git', require: false
```

```
# Gemfile.lock
GIT
  remote: https://github.com/prawnpdf/prawn-table.git
  revision: da0423372f06f79c2b1d45c1d6a45f6e0381b7c9
  specs:
    prawn-table (0.2.3)
      prawn (>= 1.3.0, < 3.0.0)

GIT
  remote: https://github.com/prawnpdf/prawn.git
  revision: ed0fd8658d3353fff14969510e7c26772a994290
  specs:
    prawn (2.1.1)
      pdf-core (~> 0.6.1)
      ttfunk (~> 1.4.0)
```

```
Fetching gem metadata from https://rubygems.org/........
Fetching https://github.com/prawnpdf/prawn.git
error: object 2aecfea9cd4415a7f2de7660009454c36fd882f2: zeroPaddedFilemode: contains zero-padded file modes
fatal: fsck error in packed object
fatal: index-pack failed

Retrying `git clone 'https://github.com/prawnpdf/prawn.git' "/Users/xbeta/.rvm/gems/ruby-2.3.0@na_main/cache/bundler/git/prawn-0b67dc9afad5b9c4bd075135bfffba355508325c" --bare --no-hardlinks --quiet` due to error (4/4): Bundler::Source::Git::GitCommandError Git error: command `git clone 'https://github.com/prawnpdf/prawn.git' "/Users/xbeta/.rvm/gems/ruby-2.3.0@na_main/cache/bundler/git/prawn-0b67dc9afad5b9c4bd075135bfffba355508325c" --bare --no-hardlinks --quiet` in directory /Users/xbeta/NA/main_site has failed.error: object 2aecfea9cd4415a7f2de7660009454c36fd882f2: zeroPaddedFilemode: contains zero-padded file modes
fatal: fsck error in packed object
fatal: index-pack failed

Git error: command `git clone 'https://github.com/prawnpdf/prawn.git'
"/Users/xbeta/.rvm/gems/ruby-2.3.0@na_main/cache/bundler/git/prawn-0b67dc9afad5b9c4bd075135bfffba355508325c" --bare --no-hardlinks
--quiet` in directory /Users/xbeta/NA/main_site has failed.

```

**Comment by pointlessone** [comment]
Yes, there are issues you're experiencing. It was decided to not fix them at the time because it would invalidate all forks and at the time (as is now) development was in progress and we didn't want to inconvenient contributors.

We may address this in the future when no active development would be in progress.

Meanwhile, as a workaround, you can disable `receive.fsckObjects` while cloning Prawn repo.

**Comment by xbeta** [comment]
@pointlessone  Hey, thanks for the speedy response. Can you please leave this issue open, so other users can still easily search this when they face the same issue again.

As for disabling `receive.fsckObjects`, I don't think we can disable specific this repo on the `Gemfile` as I think it's a good idea to keep that git option as enabled for everything else.

What are some good alteratives?

**Comment by pointlessone** [comment]
You're right that you can not set this in the Gemfile. However your git config is different to default anyway. Also consider that you can not do anything about fsck error in received packages other than reporting upstream so value is rather limited in that regard.

Alternatively, you can [override this specific issue](https://git-scm.com/docs/git-config#git-config-receivefsckltmsg-idgt) to be a warning instead of an error.

**Comment by xbeta** [comment]
@pointlessone I tried your suggestion with setting `receive.fsckObjects` to false for `.git/config`, but still failed. I believe the fsck results in error, not a warning.

**Comment by teor2345** [comment]
@xbeta:
> @pointlessone I tried your suggestion with setting `receive.fsckObjects` to false for `.git/config`, but still failed. I believe the fsck results in error, not a warning.

`fetch.*` is the setting for clones and fetches, not `receive.*`. See:
https://git-scm.com/docs/git-fsck#Documentation/git-fsck.txt-fsckltmsg-idgt

In recent versions of git, you can set `fetch.fsck.skipList` to a list of the failing object IDs. That's the best way to resolve this issue, because other objects are still checked.

Here's a working config that allows all operations on those objects:

.gitconfig:
```
[fetch]
    fsckobjects = true
[fetch.fsck]
    skipList = ~/.git_fsckskiplist
[receive]
    fsckObjects = true
[receive.fsck]
    skipList = ~/.git_fsckskiplist
[fsck]
    skipList = ~/.git_fsckskiplist
```

~/.git_fsckskiplist:
```
2aecfea9cd4415a7f2de7660009454c36fd882f2
30cbfed781a571ef2ed914ab7e497fc17ffdf085
```

**Comment by xbeta** [comment]
No longer working on this project, closing it.
