### ISSUE TITLE
Active Storage anyone?

### ISSUE THREAD

**Issue by timokleemann** [prawnpdf/prawn#1111]
Has anyone ever managed to get Prawn PDF and [Active Storage](https://edgeguides.rubyonrails.org/active_storage_overview.html) working together?

I've spent all day trying to render an image from Rails' Active Storage in my Prawn PDF. Nothing really worked. This is one of my countless attempts:

```
path = @view.rails_blob_url(@logo, :host => "localhost:3000", :protocol => "http")
image path
```

It's not working, though.

When I try to open the PDF, I get this error:

> ArgumentError in InvoicesController#show http://localhost:3000/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBGdz09IiwiZXhwIjxudWxsHCJwdXIiOiJibG9iX2lkIn19--06167c36c283f6d5de63ae306b721310af11f70e/Test-Logo.png not found

When I use `image open(path)` instead, I get a `Net::ReadTimeout` error.

When I copy that exact same URL into my browser, the image shows up as expected. 5 minutes later it expires (?).

What am I missing?

**Comment by Subtletree** [comment]
A bit late and might not be what you're looking for. I'm doing this which works:
```
logo = model.logo.download
logo_data = StringIO.open(logo)
image logo_data
```

**Comment by timokleemann** [comment]
That worked! Thanks a lot, @Subtletree!

**Comment by atstockland** [comment]
How would this work with a variant?  I'd like to shrink and compress the image on the way in to make the PDF a smaller file.

image StringIO.open(
    @logo.variant(resize_to_limit: [500, 500], quality: 70, strip: true).processed.blob.download
)

doesn't seem to render a smaller image...seems to still be the original full size image.  Anyone doing something like this in Prawn?

**Comment by gettalong** [comment]
@atstockland This has nothing to do with Prawn anymore. Prawn's `#image` method accepts an IO object. So if you library provides an IO for the image, then you can use that object directly. Otherwise, if the library returns the image as binary blob in a string, use `StringIO.new(image_blob)`.

So, check if `@logo.variant(resize_to_limit: [500, 500], quality: 70, strip: true).processed.blob.download` actually returns a usable image by saving it somewhere and inspecting it. Also check it has the size you expect.
