### ISSUE TITLE
Language subscripts not working properly for Khmer

### ISSUE THREAD

**Issue by sharathkumar** [prawnpdf/prawn#1170]
I am using Khmer language in my project. But when using a font in Prawn the subscripts are replacing with + symbol.
@prawnpdf

Actual Result :  
![Screenshot 2020-08-28 at 10 31 44 AM](https://user-images.githubusercontent.com/3734452/91523857-68364f80-e91b-11ea-828d-6ae68372f1c9.png)

**Expected Result : សង្កាត់ ផ្សារដើមគរ, ខណ្ឌទួលគក, ភ្នំពេញ**

**Comment by gettalong** [comment]
I'm not familiar with Khmer and how subscripts work there but this is most probably be a limitation of prawn/ttfunk since it doesn't support advanced glyph positioning via GSUB/GPOS font tables.

If you could provide a small sample script together with the appropriate font file, it might help to find the problem.
