### ISSUE TITLE
height_of returns same height for every character

### ISSUE THREAD

**Issue by smithtim** [prawnpdf/prawn#1180]
Whereas `width_of` returns different widths for different characters, `height_of` seems to return the same height for every character.  Is this the expected behavior?  If so, is there a way to get the actual heights?

```ruby
pdf = Prawn::Document.new

puts pdf.width_of 'A'
puts pdf.width_of 'a'

puts pdf.height_of 'A'
puts pdf.height_of 'a'
```

outputs

```
8.004
6.672
13.872
13.872
```

**Comment by gettalong** [comment]
The width of each character has to be different because we need it to calculate the width of a line. However, the height of a line should *not* depend on the characters therein. For example, a line with just `a` should have the same height as a line with just`T`, given they use the same font and font size. Otherwise the lines would not look good/correct. *How* the height is calculated is kinda complicated and may not be the same everywhere.

I don't know if Prawn provides direct access to the font to get the real height but you can always fall back to ttfunk to get the correct values.
