### ISSUE TITLE
2.4.0 tag is missing, where is released 2.4.0 gem come from?

### ISSUE THREAD

**Issue by metalefty** [prawnpdf/prawn#1236]
2.4.0 is released on rubygems.org but it is not tagged on GitHub. Which commit is 2.4.0 is built from? Please tag it.

BTW, could you consider making a new release 2.4.1 or 2.5.0 that includes 3658d5125c3b20eb11484c3b039ca6b89dc7d1b for Ruby 3.1 compatibility?

**Comment by metalefty** [comment]
Regarding the new release, I found #1195.

**Comment by gettalong** [comment]
There is a tag called 2.4.0 - see https://github.com/prawnpdf/prawn/releases/tag/2.4.0, referencing commit https://github.com/prawnpdf/prawn/commit/46ac6969a94a29d45fd5eec662cfc9c3622619d1.

**Comment by psibre** [comment]
But wouldn't it be great to add a proper release under https://github.com/prawnpdf/prawn/releases?

**Comment by gettalong** [comment]
@psibre I don't think that everyone has the same notion of a "proper release". Github releases are nice if you wanna go down that road but it adds another step to the release process and doesn't provide any benefits (as far as I'm familiar with that feature of Github).

In my opinion a "proper release" for a Ruby gem is... creating the gem, pushing it to the main central repository (i.e. rubygems.org) and having a list of changes available somewhere. Having an additional tag in the source code repository is nice for people using such a tag but if you are strict you would need to compare the files of the tagged commit to the released gem to ensure they are the same.

**Comment by pointlessone** [comment]
I was experimenting a bit with putting up releases on GH. There are benefits to it (e.g. GH publishes a feed to releases) but as @gettalong said, it's another step in the release process. On top of that, there's a downside to it, too. Releases automatically attach a tarball to a release which is _not_ the artefact of a release. I can not figure out how to make it stop doing that. GitHub has a feature to publish packages but I don't want to use it for releases because we already have a canonical package store: RubyGems. I don't want to add another one as it might be confusing. And it's yet another step in the release process.

**Comment by psibre** [comment]
Thanks for the feedback, and fair enough!

I was just casually dropping by the repo, and seeing this at the right (expecting 2.4.0):
![image](https://user-images.githubusercontent.com/1278639/174056723-39cdb11e-57b4-41ee-b0c2-efa17be12b27.png)

I agree that Releases is not a feature we asked for, or that your release process needs, but for random people on GitHub, it might cause confusion, or perhaps lead them to believe that there is a divergence between the package on rubygems.org, and the maintainers of the GitHub repo...

Also, you *do* have the releases up to 2.3.0, so I suspected it might just be an oversight. =P
