### ISSUE TITLE
"Cursor" with repeater dynamic not working

### ISSUE THREAD

**Issue by phamdat8** [prawnpdf/prawn#1306]
when I use dynamic false
```
repeat(:all) do
  # some code for header
  @height = cursor
end
bounding_box [bounds.left, @height] do
  #somre code for body
end
```
it work fine and my body render under header
when I use dynamic true
```
repeat(:all, dynamic: true) do
  # some code for header
  @height = cursor
end
bounding_box [bounds.left, @height] do
  #somre code for body
end
```
the @height is not set, the reason is repeat(with dynamic) render after each other
can anybody help me how to calculate the header height?

**Comment by pointlessone** [comment]
I'd suggest this is actually a bug with non-dynamic repeaters.

A static (non-dynamic) repeater evaluates your code once and create a stamp. It just happens to evaluate your block immediately. That's why you have `@height` defined at all.

Dynamic repeaters are executed at the very end. That is, your block is saved and when you call `render` that block is executed on all pages. So the variable gets set but _after_ the bounding box is set.

Instead of a repeater I'd suggest defining a method or a lambda and call it manually it on every page. This way you can be sure the code is executed in order.

```ruby
def draw_header (document)
  # some code for header
  @header_height = document.cursor
end

Prawn::Document.generate('my-doc.pdf') do |doc|
  on_page_create { |document| draw_header(document) }

  draw_header(doc)
  bounding_box [bounds.left, @header_height] do
    # some code for body
  end

  start_new_page

  draw_header(doc)
  bounding_box [bounds.left, @header_height] do
    # some code for another body
  end
end
```

**Comment by phamdat8** [comment]
Thank you, but I use prawn-table for my body, so my 
```ruby
  # some code for body
  ```
is multiple pages. that reason why I use repeater.
Do you have any solution for this?

**Comment by pointlessone** [comment]
I believe `on_page_create` callback should work here.
