### ISSUE TITLE
The Return of the Embedded Font Issue

### ISSUE THREAD

**Issue by TastyPi** [prawnpdf/prawn#1346]
Prawn 2.5.0 appears to have reintroduced this old "Cannot extract the embedded font" issue https://github.com/prawnpdf/ttfunk/issues/73

Using the exact same code to render a PDF using 2.4.0 does not have this issue.

**Comment by pointlessone** [comment]
Do you experience this issue if you disable font subsetting?

**Comment by TastyPi** [comment]
I tried with `subset: true` and `subset: false`

**Comment by pointlessone** [comment]
Could you please provide a minimal reproduction script and fonts you have issues with?

**Comment by pointlessone** [comment]
Also could you please list versions of the gems you use?

```sh
gem list --all --exact prawn ttfunk pdf-core
```

**Comment by TastyPi** [comment]
I tried a minimal example that just sets the font, but that did not reproduce the issue so it's definitely something deeper. Our PDF generation code is pretty complex, so it'll take me a while to create a minimal example, not sure when I'll find the time :confused:.

Before downgrading (with issue):

```
bundle list | grep -E 'prawn|ttfunk|pdf-core'
  * pdf-core (0.10.0)
  * prawn (2.5.0)
  * ttfunk (1.8.0)
```

After downgrading (no issue):
```
bundle list | grep -E 'prawn|ttfunk|pdf-core'
  * pdf-core (0.9.0)
  * prawn (2.4.0)
  * ttfunk (1.7.0)
```

**Comment by TastyPi** [comment]
Thanks to the magic of Ruby, I've managed to log every call made to the `Prawn::Document` instance, and successfully reproduced the issue. I'm just cleaning it up to remove specific details and make it minimal.

**Comment by pointlessone** [comment]
Thanks.

**Comment by coorasse** [comment]
Thanks for the deep dive @TastyPi, you helped us! 
Will you open an issue on ttfunk, or is the team aware of it?
We locked ttfunk `gem 'ttfunk', '< 1.8.0'` in the meantime.

**Comment by TastyPi** [comment]
Filed https://github.com/prawnpdf/ttfunk/issues/102, I wasn't sure if @pointlessone was going to do it as they appear to be the main ttfunk developer.

**Comment by pointlessone** [comment]
It's not immediately obvious where the issue is. PDF has rather complex relationships with fonts. Fonts are partially represented/duplicated in native PDF structures, some essential parts (according to fonts specs) of fonts are ignored in PDF, renderers don't exactly follow specs (both PDF and fonts). So the issue might not be in TTFunk even if it's related to fonts. Let's keep it as is, I'll figure it out when I'll have time to work on this.

**Comment by Salman464** [comment]
Encountered the same error recently `Cannot extract the embedded font '3a9d5f+Recoleta-Bold'. Some characters may not display or print correctly.`

Faced issue on the versions:

- pdf-core (0.10.0)
- prawn (2.5.0)
- ttfunk (1.8.0

Resolution:
Downgraded gems to resolve:

- pdf-core (0.9.0) (automatically downgraded with prawn and ttfunk)
- prawn (2.4.0)
- ttfunk (1.7.0)

I can confirm that downgrading to previous versions of prawn and ttfunk resolved the issue. not sure though if the issue is from ttfunk  or prawn upgrade

**Comment by afdev82** [comment]
> Do you experience this issue if you disable font subsetting?

I had the same error and I have "solved" it disabling the subsetting when registering the font family.
If I can inspect something to provide some help to solve the issue, let me know what I can do.
Thank you.

**Comment by timokleemann** [comment]
I can confirm that this Gem combination fixed the issue in my Rails 7 application:

```
gem "pdf-core", "0.9.0"
gem "prawn", "2.4.0"
gem "ttfunk", "1.7.0"
```

The special characters that were previously missing in Acrobat Reader are now visible again.

**Comment by dacook** [comment]
Although the problem is with ttfunk, the issue is still present in Prawn so I would consider this issue open.

@coorasse  mentioned:
> We locked ttfunk `gem 'ttfunk', '< 1.8.0'` in the meantime.

However I don't think anything has changed in the Prawn codebase (see https://github.com/prawnpdf/prawn/blame/master/prawn.gemspec#L52).

So this is still a problem on the current Prawn release and master branch.

**Comment by donmb1** [comment]
> I can confirm that this Gem combination fixed the issue in my Rails 7 application:
> 
> ```
> gem "pdf-core", "0.9.0"
> gem "prawn", "2.4.0"
> gem "ttfunk", "1.7.0"
> ```
> 
> The special characters that were previously missing in Acrobat Reader are now visible again.

this worked for us

**Comment by samyouel** [comment]
same here... had to downgrade to `2.4.0` to get it to work again. Is `ttfunk@1.7.0` an option as a dependency for prawn, was @dacook mentioned?

**Comment by JosephTico** [comment]
Still an issue, this shouldn't be closed

**Comment by aleksmsd** [comment]
Can confirm a similar issue with various glyphs missing from `subset: true` embedded truetype fonts (Note, different glyphs missing from different fonts) Locking `gem 'ttfunk', '< 1.8.0'` seems to have fixed the issue on my end as well.

Any news?

Edit: `gem 'prawn', '~> 2.3'`, `ruby '3.3.9'`

**Comment by jfr** [comment]
+1 shouldnt be a closed issue, can the ttfunk dependency be fixed?

**Comment by sled** [comment]
looks like this got fixed with https://github.com/prawnpdf/ttfunk/commit/6bc9950a4a2110e84a29eff850e0e61fda171484 but still awaiting release...
