### ISSUE TITLE
Can we import whole another PDF append to  generated pdf ? 

### ISSUE THREAD

**Issue by ptmpn** [prawnpdf/prawn#348]
Hi

Can we import whole another PDF to append generated PDF ?

For example:

imported_PDF has 4 pages

I need to generate PDF and put some text on page 1 and start to import message from imported_PDF append to text generated in PDF (at lease start on page 2)

For now I used syntax like this :

``` ruby
Prawn::Document.new(:skip_page_creation => true, :page_size =>"A4", :template => imported_pdf_path) do
  # ...
  # some stuff for imported_PDF ...
  # ...

  go_to_page(0)
  start_new_page
  # ...
  # some generated text (dynamic text depend on data in DB)
  # ...

```

Problem is: when generated text was longer than 1 page length it start to put text on page 2 and use page 1 of imported_PDF as background image (imported text from another PDF was overlapped by generated text)

How can I get something like:

```
--page1----------
generated data
generated data
generated data
generated data
generated data
--page2----------
generated data
generated data
generated data
imported data
imported data
--End page ----
```

or 

```
--page1----------
generated data
generated data
generated data
generated data
generated data
--page2----------
generated data
generated data
generated data


--page3----------
imported data
imported data
imported data
imported data
imported data
--End page ----
```

for now i get

```
--page1----------
generated data
generated data
generated data
generated data
generated data
--page2----------
generated overlap with imported data   <= CANNOT READABLE
generated overlap with imported data   <= CANNOT READABLE
generated overlap with imported data   <= CANNOT READABLE
imported data 
imported data 
--End page ----
```

**Comment by jasonperrone** [comment]
Any chance this answer has changed since it was asked 6 years ago? I really need the ability to take a PDF I generated with Prawn, and while I am generating it, before I render it, append an existing PDF file to it, and then render the whole thing with encryption. Ideally, it would be nice to slightly modify the pages of the existing file I am appending, say, to put the same header on it as the generated portion.

Right now, what we have to do is use ImageMagick to turn the existing PDF into an image file and then embed it as an image, but oh my God is that process slow. Not sure if it's ImageMagick that's slow, but I imagine it is. But it's really flaky to have to turn a PDF into an image just go I can append it to the Prawn PDF.

The pdftk doesn't really do it for me because I don't want a reliance on a command line tool being installed first. I just wonder if since this question was asked has Prawn added the ability to just add a PDF to the PDF you're generating.

**Comment by jds13** [comment]
Run it as an external process, with exec.

**Comment by gettalong** [comment]
@jasonperrone Have you tried using the `prawn-templates` gem (see https://github.com/prawnpdf/prawn-templates). It should allow you to add pages from an existing PDF to a Prawn document.

**Comment by jasonperrone** [comment]
I think I'm a little worried by nearly every single sentence in the README LOL.

**Comment by gettalong** [comment]
:smile: It should work fine though for most cases. Just be aware that `pdf-reader`, on which this gem is built, is not a full PDF reading library and doesn't support all PDFs.
