### ISSUE TITLE
CMYK pdf inverts color when opened in Illustrator

### ISSUE THREAD

**Issue by robzolkos** [prawnpdf/prawn#359]
I have produced a CMYK PDF using prawn.  The background image I used is a cmyk jpg and then apply prawns text commands to it.   When I open the PDF in any application it looks correct.  However opening it in Adobe Illustrator, the background has inverted colors.

I am not sure what is causing this or how to resolve.  But I need to be able to open the PDF generated by prawn and edit it in Illustrator.  Hopefully someone has heard of this happening and knows a fix.  

Ive put an example PDF in this repo  https://github.com/RobZolkos/pdfissue

**Comment by Screwface** [comment]
Don't worry people, its simply that your RGB PDF is being automatically converted to CMYK witch creates that bug. Follow those steps and you should be OK.

1. open your file (just like you did) in illustrator.
2. delete the artwork (PDF) leaving the artwork size only
3. File > Document Color Mode > RGB Color       *(remember?... your PDF is in RGB!)
4. File > Place.... find you file on your computer.

Like magic, your issue is no more !

**Comment by elsurudo** [comment]
@Screwface What if we want out PDF to be in CMYK, though?

**Comment by elsurudo** [comment]
I would propose to re-open this issue. I don't believe it is fixed, and the workaround is not a tenable one.

In short: When opening a prawn-generated CMYK PDF in illustrator with embedded JPGs that are also in CMYK, the embedded JPGs colors are inverted.

**Comment by gettalong** [comment]
@elsurudo Have you tried PDFs generated with other applications if they exhibit the same issue? E.g. creating a PDF from a LibreOffice Writer document that contains a CMYK JPG? @ghinda said that the same problem applies to other libraries too, so maybe it is something on Illustrator's side...

**Comment by teambuktu** [comment]
I had the same problem with CMYK PDFs generated with TCPDF or FPDF. They look fine in Acrobat Reader, Photoshop, etc. However, Illustrator shows them inverted. I found a solution:

- Invert the CMYK JPEG before you insert it into the PDF
- Change the source code (in your PDF library), so that
`/Decode [0 1 0 1 0 1 0 1]` 
is used instead of 
`/Decode [1 0 1 0 1 0 1 0]`

Illustrator obviously ignores this string. Other PDF readers will invert the inverted CMYK back (basically).

**Comment by cxgraphics** [comment]
This is how I did it:

Open the pdf file in Acrobat Pro, choose “Edit PDF”, do any minor changes, then save the file.

Now the pdf should appear in correct colors in other Adobe softwares.

**Comment by lukacsaron** [comment]
Hey @teambuktu,

I really like your workaround. Hopefully, it'd save my ass on a project. Could you please clarify the "Change the source code (in your PDF library), so that" part regarding to an embedded image with jsPDF?

Thanks a lot,
Aron

**Comment by teambuktu** [comment]
> Hey @teambuktu,
> 
> I really like your workaround. Hopefully, it'd save my ass on a project. Could you please clarify the "Change the source code (in your PDF library), so that" part regarding to an embedded image with jsPDF?
> 
> Thanks a lot,
> Aron

I'm not sure about jsPDF. After generating your PDF open it in a text viewer and try to do a full text search for "CMYK" and locate a line like this:

<</Type /XObject /Subtype /Image /Width 2929 /Height 1535 /ColorSpace /DeviceCMYK /Decode [0 1 0 1 0 1 0 1] /BitsPerComponent 8 /Filter /DCTDecode /Length 70659 >> stream

If the bits behind decode are not in this order, it seems to cause problems. That's why I inverted the CMYK jpeg and made sure the Decode value is [0 1 0 1 0 1 0 1]

Now you would have to find out the function in the source code that generates this Decode-String. It might have something to do with the line "options.push({ key: "Decode", value: "[0.0 1.0 0.0 1.0 0.0 1.0]" });" in
https://github.com/MrRio/jsPDF/blob/master/src/jspdf.js

But that's just a quick guess, which might be wrong. 

I hope I could give you a first clue.
