### ISSUE TITLE
Add support for otf font

### ISSUE THREAD

**Issue by lawerna** [prawnpdf/prawn#470]
otf-fonts are not working.

Would be great if prawn could support also otf fonts.

**Comment by mojavelinux** [comment]
We really need to revisit native OTF support for Prawn, even if ask for community help. It's use is growing, particular for CJK support and forcing people to convert to TTF or find a TTF version of the font is tedious. I don't know how you want to handle big roadmap items, but I think it's important to at least communicate that help is needed in this area...esp if we hope to help from font specialists.

**Comment by sandal** [comment]
@mojavelinux The state of this issue is the same as any other: If you or someone else implement or do useful research, it'll move along. There are many areas we're missing important parts for in Prawn, and the best way to fill them in is to implement yourself when you have a direct need. A patch is certainly welcome!

**Comment by sandal** [comment]
@mojavelinux The state of this issue is the same as any other: If you or someone else implement or do useful research, it'll move along. There are many areas we're missing important parts for in Prawn, and the best way to fill them in is to implement yourself when you have a direct need. A patch is certainly welcome!

**Comment by sandal** [comment]
@mojavelinux The state of this issue is the same as any other: If you or someone else implement or do useful research, it'll move along. There are many areas we're missing important parts for in Prawn, and the best way to fill them in is to implement yourself when you have a direct need. A patch is certainly welcome!

**Comment by mojavelinux** [comment]
I have absolutely no time, nor the required experience, to tackle this issue. I am already maxing out my days working on open source documentation tools. I'm merely pointing out that it's going to quickly become a sore spot in Prawn if we, as a community, don't start advocating for / championing interest in solving it. In my opinion, an *open* issue is what helps communicate that point, not a closed one.

**Comment by sandal** [comment]
@mojavelinux We don't track requests without significant research attached. If we did (and we have in the past) we'd end up with hundreds of stale tickets with no progress other than the occasional "when are you going to get around to implementing this". The answer to that question right now is *never*. But it can change if we find an implementer.

Please understand that we don't use our tracker for the purpose you have in mind, that this is actually a low priority change from a maintenance perspective (even if its very useful), and that our policy still leans heavily towards assisting implementers rather than maintaining a wish list of things we hope someone will eventually work on.

If this issue is important to you, the best way to help is to write a blog post, tweet, or otherwise ask around to find someone who is willing to work on this. A clear ticket that outlines implementation details and relevant documentation, or a pull request is what will get this into a work-in-progress / planned development state.

**Comment by sandal** [comment]
@mojavelinux We don't track requests without significant research attached. If we did (and we have in the past) we'd end up with hundreds of stale tickets with no progress other than the occasional "when are you going to get around to implementing this". The answer to that question right now is *never*. But it can change if we find an implementer.

Please understand that we don't use our tracker for the purpose you have in mind, that this is actually a low priority change from a maintenance perspective (even if its very useful), and that our policy still leans heavily towards assisting implementers rather than maintaining a wish list of things we hope someone will eventually work on.

If this issue is important to you, the best way to help is to write a blog post, tweet, or otherwise ask around to find someone who is willing to work on this. A clear ticket that outlines implementation details and relevant documentation, or a pull request is what will get this into a work-in-progress / planned development state.

**Comment by benhourigan** [comment]
+1

**Comment by mojavelinux** [comment]
Related issue, which includes an open offer to help implement this feature: #893.
