### ISSUE TITLE
Reimplement Document#group without transactions

### ISSUE THREAD

**Issue by practicingruby** [prawnpdf/prawn#678]
This probably means creating a limited version of what we have before that uses height calculations rather than transactions to decide what can fit on a page.

**Comment by romand** [comment]
here is what I've got, it hadles bounding boxes correctly and works for subclasses of `Document`
https://gist.github.com/a0a4c07aac98e28ac634
based on @ddengler 's code

**Comment by romand** [comment]
@ollym here is what I've got, it hadles bounding boxes correctly and works for subclasses of `Document`
https://gist.github.com/a0a4c07aac98e28ac634

**Comment by huwd** [comment]
Hello everyone,

Does anyone have a running workaround for this, @romand the Gist link above is now dead and it looks like it's been a while since anyone spoke about this - is there currently a way to stop paragraphs breaking across a page/column boundary?

**Comment by ddengler** [comment]
@huwd does my grouping gem https://github.com/ddengler/prawn-grouping solve this for you? If not, please let me know in the projects issue tracker. I did not have the time to update the project recently, but if there are fundamental issues with the approach I will look into it again for you.

**Comment by huwd** [comment]
:+1: For future finders of this thread, I can confirm the gem @ddengler wrote works beautifully (2016 edition of 'this works') - used in a Rails 5 app with Prawn 1.0.0. :tada: Thank you!

**Comment by packetmonkey** [comment]
This issue was left open to see if there was a better solution for this problem than the prawn-grouping gem. It looks like nobody has come up with one and it's solving real issues so I created a [Related Gems](https://github.com/prawnpdf/prawn/wiki/Related-Gems) wiki page and added it there for people to find it (with some other gems I know about off hand).

@ddengler if there is anything in Prawn we could add to make implementing your gem easier, let us know. Happy to help extend the prawn ecosystem.

**Comment by ddengler** [comment]
@packetmonkey thanks for mentioning the project in the wiki and for the offer to open up prawn to the plugin. I will look into the latest prawn version, update the plugin and let you know if I have any API related issues.
