### ISSUE TITLE
How to rotate content to use the full post-rotation space?

### ISSUE THREAD

**Issue by airblade** [prawnpdf/prawn#805]
I have a small page in landscape format containing some text and an image.  I would like to rotate the text and image through 90deg while keeping the page as landscape, so that when you hold the printed page in portrait format the text flows down the page in the normal way.

To do this I set the width of the content to the landscape-height and the height of the content to the landscape-width, and offset the origin appropriately, then rotate everything about the centre of the page using the `rotate` method from `graphics/rotate.rb`.

However the resulting content is rather short.  The width of the "sideways" (i.e. rotated) content is correct but the height of the "sideways" text is only as high as the landscape-height, not the portrait-height.

Is this because you can't write text outside the page area (in my pre-rotation step)?  Is there any way around this?

**Comment by sandal** [comment]
It does sound like the problem you're having is that Prawn is wrapping text based on the portrait boundaries. I'd have to give this some thought, because I've never tried to do this sort of thing before.

You may want to see if any of the existing templates in https://github.com/jordanbyron/prawn-labels work for you, and then rotate the text and image on a per-label basis.

I'll leave this open as something that might potentially be a missing feature in Prawn, at least until we explore what options we have. I'm not sure when I'll find time to investigate, but please update if you find a suitable workaround.

**Comment by airblade** [comment]
I believe I've been overthinking this and the solution is trivial.

In my particular use case I am rendering labels for a label printer.  Unlike printing A4 / Letter sheets of labels, label printers print off a roll so you can say there is one label per "page".  To print a label "sideways" (a portrait label on its side) one just needs to set the label's dimensions portrait-style (same as the page), then set the layout to landscape in the printer settings when printing.  In other words, let the OS's printing system rotate the label.
