### ISSUE TITLE
Add option `:line_height` to `text_box`

### ISSUE THREAD

**Issue by andre1810** [prawnpdf/prawn#836]
Add option `:line_height` to `text_box` to support different line heights.

**Comment by practicingruby** [comment]
Hi, 

This seems like something worth adding, but in order to re-open this ticket, we'll need a lot more detail on how the feature should work, as well as some research on how to implement it.

We try to make sure that unless there's an implementer for an idea, we only keep open tickets for detailed feature requests and bug reports.
