### ISSUE TITLE
No .ttf fonts in Prawn::DATADIR for prawn-2.0.1

### ISSUE THREAD

**Issue by rascal-hats** [prawnpdf/prawn#841]
Installing prawn as a gem through `gem install prawn` (from rubygems.org) yields this result:

```
$ ls prawn-2.0.1/data/fonts/
Courier-Bold.afm         Courier.afm                Helvetica-Oblique.afm  Symbol.afm            Times-Italic.afm
Courier-BoldOblique.afm  Helvetica-Bold.afm         Helvetica.afm          Times-Bold.afm        Times-Roman.afm
Courier-Oblique.afm      Helvetica-BoldOblique.afm  MustRead.html          Times-BoldItalic.afm  ZapfDingbats.afm

```

Installing prawn through my Gemfile as `gem 'prawn', git: "https://github.com/prawnpdf/prawn.git"` yeilds this result:

```
$ ls prawn-af1f659bf8cb/data/fonts/
Courier-Bold.afm         DejaVuSans-Bold.ttf  Helvetica-BoldOblique.afm  Panic+Sans.dfont      Times-Italic.afm
Courier-BoldOblique.afm  DejaVuSans.ttf       Helvetica-Oblique.afm      Symbol.afm            Times-Roman.afm
Courier-Oblique.afm      Dustismo_Roman.ttf   Helvetica.afm              Times-Bold.afm        ZapfDingbats.afm
Courier.afm              Helvetica-Bold.afm   MustRead.html              Times-BoldItalic.afm  gkai00mp.ttf
```

According to the [2.0.1 tree](https://github.com/prawnpdf/prawn/tree/2.0.1/data/fonts) these fonts should have been included, but https://rubygems.org/ seems to exclude them?

```
$ gem source
*** CURRENT SOURCES ***

https://rubygems.org/

$ gem --version
2.4.6
```

Hoping this is just something obvious I've missed.

**Comment by practicingruby** [comment]
We stopped packaging the TTF files in Prawn's gem several years ago, because they are meant for testing purposes only.

If you are trying to use Prawn for generating PDFs, you'll need to grab TTF files for whatever custom fonts you're using.

If you are repackaging Prawn for an OS distribution, please build from our git tags rather than unpacking the gems..

**Comment by rascal-hats** [comment]
Okay, glad I wasn't doing something dumb.

Would you like some help updating the PDF manual? It still refers to .ttf files residing inside Prawn::DATADIR in several locations.

**Comment by practicingruby** [comment]
@rascal-hats: It does reference `Prawn::DATADIR`, because the manual is generated from the source code in the examples themselves. In other words, the code samples you see in the PDF are actually run to generated the documentation, they're not just snippets.

Adding some clarifying comments might help, though!
