### ISSUE TITLE
Outline suffers the too much magic bug

### ISSUE THREAD

**Issue by tvw** [prawnpdf/prawn#878]
Outline provides a nice DSL, but it uses instance_eval, which prevents the given block to access the objects methods, from where outline is called.

I wonder, whether a DSL, which uses yield, is more flexible for the enduser, because then they can access their objects methods and attributes:

```ruby

outline do |o|
    o.section("Section level 1", destination: level_1_sect_page_no) do |s1|
        s1.section("Section level 2", destination: level_2_sect_page_no) do |s2|
            s2.page(title: "Page 1", destination: @my_page_no)
        end
    end
end

```

**Comment by crazymykl** [comment]
As a workaround, use local variables, which will still be visible in the eval'd scope.

**Comment by practicingruby** [comment]
For now, use the solution recommended by @crazymykl. I'd be open to rethinking this UI, but I'm not sure that a yielding API is the way to go there, and right now we're focused on internal improvements to Prawn rather than API changes.

Closing because we don't track feature requests, but this is something to think about in a (much later) version of PrawnPDF.
