### ISSUE TITLE
prawn-2.0.1 is not the same code in rubygems 

### ISSUE THREAD

**Issue by liuganggang** [prawnpdf/prawn#901]
Hi, Prawn at tag 2.0.1 from git and rubygems is different.

Can you push and update rubygems prawn-2.0.1?

Thinks. :)

**Comment by packetmonkey** [comment]
Hi, I am highly reluctant to overwrite what has been pushed up to github because I don't want to change code out from underneath people without them knowing.

I didn't cut the 2.0.1 gem release but I will try to be very careful moving forward that what is tagged on the stable branch is what exactly is pushed up to ruby gems.

Is there a specific problem this is causing you? I'm not saying it's an issue but I am curious to what workflow it's impacting.

**Comment by liuganggang** [comment]
I get this error.
```
ArgumentError: /Users/liugang/.rvm/gems/ruby-2.1.3/gems/prawn-2.0.2/data/fonts/gkai00mp.ttf not found
```
:)

**Comment by liuganggang** [comment]
I fix it by download gkai00mp.ttf to public folder.
enn.
Thank you for your help!
:)

**Comment by packetmonkey** [comment]
Glad to hear it's sorted out. Closing the issue.
