### ISSUE TITLE
#width_of with inline_format does not take into account trailing space

### ISSUE THREAD

**Issue by edborden** [prawnpdf/prawn#909]
`width_of("string ",inline_format:true)` ignores the trailing space. I've compensated by manually adding additional width where necessary (my usage of a trailing space is consistent). Using `width_of` without options or with `style: :bold` do return the correct width.

**Comment by packetmonkey** [comment]
The formatted arranger does [intentionally omit trailing space](https://github.com/prawnpdf/prawn/blob/master/lib/prawn/text/formatted/arranger.rb#L66) when doing it's finalization which is why the string it returns doesn't have trailing space so your line width calculation wouldn't cover it.

From my understanding however when you go to print the formatted line with the trailing space it should be stripped out as well.

Do you have a situation where you are using `inline_format: true` for the width_of but not on the final text draw? Or am I misunderstanding?

**Comment by edborden** [comment]
Well, I compensated for the trailing space being stripped out in my width calculation, then put my text into a bounding box with that width, that way on the page the trailing space is there in practice simply as distance between characters.  But it's not ideal for my application, I'd rather have a real width calculation and retain the trailing space.

Regardless, if this was your intention, this issue can at least serve as some additional documentation.

**Comment by packetmonkey** [comment]
Given how we remove it from the finalized line that is the intention. However ruby normally doesn't consider a non-breaking space as 'whitespace' in the strictest sense so you may be able to append that to your string for spacing and have everything work as you would like.

```ruby
irb(main):001:0> "string ".strip
=> "string"
irb(main):002:0> "string\u00A0".strip
=> "string "
```
