### ISSUE TITLE
NoMethodError: undefined method `real_params' for PDF::Core:Module 

### ISSUE THREAD

**Issue by gillesmathurin** [prawnpdf/prawn#927]
Hi,
I am trying to generate a pdf document with an embed image as background image but I am getting this error :
`NoMethodError: undefined method 'real_params' for PDF::Core:Module
from /Users/gillesmath/.rvm/gems/ruby-2.2.2@aim/gems/prawn-2.0.2/lib/prawn/images.rb:122:in 'embed_image'`

I am using Prawn 2.0.2 and my code looks like this :

```ruby
class CertificatesPDF < Prawn::Document

  def initialize(params)
    super font_size: 10,
          margin: 0,
          page_size: "A4",
          page_layout: :landscape
    @params = params
    header
  end

  def header(title=nil)
    y_pos = cursor
    image_file = image_file_for_course(@params[:course_title])
    image image_file, at: [0, y_pos], width: 841.89
    move_down 20
    bounding_box([0, 377], width: 841.89, height: 400) do
      pad_bottom(79) {
        text Time.now.strftime("%B %Y"), align: :center, size: 18
      }
      pad_bottom(60) {
        text @params[:user_name], align: :center, size: 20
      }
      text @params[:course_title], align: :center, size: 14
    end
  end
```

**Comment by practicingruby** [comment]
I'm not sure what the cause of this issue was here, but from the looks of it, it might be a mismatch between Prawn and PDF::Core versions, but if that were the case I'd guess it was a configuration issue on your end, @gillesmathurin.

We'd need a minimal reproduction that doesn't depend on your application code and includes all necessary code to run in order to investigate further.
