### ISSUE TITLE
Prawn::Errors::CannotFit - Table's width was set too small to contain its contents (min width 523.0, requested 498.48)

### ISSUE THREAD

**Issue by railsfactory-bhaskararao** [prawnpdf/prawn#944]
Here is my code
```ruby
def build_pdf
   filename = get_filename
   Tempfile.new(filename).tap do |pdf_file|
     pdf = Prawn::Document.new(:template => @@summary_sheet_form) 
     pdf.start_new_page
     pdf.table(build_table_data, :column_widths => [125, 343, 55], :cell_style => { :inline_format => true }) do
      cells.padding = 5
      cells.min_width = 523
      cells.border_width = 1
      row(0).font_style = :bold
    end
    pdf.render_file pdf_file.path
  end
end
```
Can someone tell me how to fix requested width to 523 and how it is taking 498.98 as requested width?

**Comment by packetmonkey** [comment]
There was a [bug](https://github.com/prawnpdf/prawn-table/pull/60) in [prawn-table](https://github.com/prawnpdf/prawn-table) that looks similar to this that got fixed.

Please check to see if using master of the prawn-table repo (with the latest release of Prawn) fixes your problem, otherwise please open an issue on that repo.

Thanks
