### ISSUE TITLE
Transparent PNGs slowing load

### ISSUE THREAD

**Issue by hoanghiep90** [prawnpdf/prawn#952]
We use prawn for PDF generation in our rails app.

```
Prawn::Document.new do
      	image "hiep_test_1.png"
end.render_file("dice.pdf")
```

When generating the PDF with transparent PNGs, the CPU alway full-load (100%) and the render is very slow.

I'm using Prawn 2.1.0, Ruby 2.2.4. Is this problem fixed in recent versions?
![hiep_test_1](https://cloud.githubusercontent.com/assets/4651640/13662455/3095f6c0-e6cd-11e5-86b3-4f3e244d2ffb.png)

**Comment by pointlessone** [comment]
Hello @hoanghiep90,

You're using the latest Prawn version. At the moment there's nothing more recent than that.

What you're seeing is the result of Prawn extracting alpha channel from your PNG image. You see, PDF doesn't natively support transparent images. So we have to apply a mask to a solid image in order to make it look as intended. For that we need to split the image into two images: a solid one, and an alpha-channel mask. Since we do it completely in Ruby it may feel slow for big images.

Now, we do it in Ruby because we want Prawn to be as portable as possible. For that we have a policy that we should not have any external dependencies, including binary extensions. There are extensions that use ImageMagick that may or may not be faster. Or you can extract alpha-channel out of your PNGs beforehand and apply the mask yourself bypassing the splitting in Prawn completely. That may be faster than what Prawn can offer right now.

We certainly care about performance and we always strive to make Prawn as fast as possible but there are limits to what Ruby can do. Yet, I would ask you to submit an example code and PNG image you experience the problem with. Just in case we're hitting some edge case which makes it unusually slow.

**Comment by packetmonkey** [comment]
As a side note, I wrote the [prawn-gmagick](https://github.com/packetmonkey/prawn-gmagick) gem to both solve the performance issues of large transparent PNG images and expand support for other image formats. It uses graphicsmagick and is a compiled native gem [for performance](https://github.com/packetmonkey/prawn-gmagick#speed)

Hopefully that helps! Otherwise we are very interested in improving the native png handler as well.
